### ISSUE TITLE
Type could not be found

### ISSUE THREAD

**Issue by yiyoMX** [henalbrod/Blazor.Auth0#1]
HI trying to setup on a Blazor (server side) project, when I replace de Index code with yours as your instructions it marks AuthenticationService, of @inject AuthenticationService _authService, as:
The type or namespace name 'AuthenticationService' could not be found (are you missing a using directive or an assembly reference?)
Also with SessionState in @if (_authService.SessionState == SessionStates.Active)

I dont know if this is normal, because it compiles but it stays on

Determining session state, please wait...

**Comment by henalbrod** [comment]
Hi, Sorry about the delay.

Are you working on Visual Studio 2019 Preview version?

**Comment by yiyoMX** [comment]
Hi, Im using Visual Studio 2019 Community v 16.0.3

**Comment by henalbrod** [comment]
Hi, that could explain the weird behavior, the current recommendation is to stick to preview version while using Blazor, I invite you to install all the required tooling following the instructions [from here ](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)

**Comment by yiyoMX** [comment]
@Pegazux I managed to make it work, I was getting an undefined state, even though I was getting a success authentication on Auth0 user logs, then I realized that the application type was set to regular web application, as soon as I changed it to SPA, it redirected correctly. Going to keep on testing. BR
Also, Im using VS 2019 16.1.0 Net Core 3 preview 5

**Comment by henalbrod** [comment]
Thanks for the info, I'll take a look and add some validations to avoid the inconsistent behavior
