### ISSUE TITLE
blazor route with encrypted parameter

### ISSUE THREAD

**Issue by MarvynHarry** [henalbrod/Blazor.Auth0#11]
How can I make my blazor application receive encrypted parameters that contain special characters such as "/" and "+" without it not understanding that the special characters are parameter dividers, please help urgently!

![image](https://user-images.githubusercontent.com/44927942/61554633-c2d05d00-aa33-11e9-8946-4dd0b4661305.png)

**Comment by henalbrod** [comment]
Close as it's not related with the project/repository
