### ISSUE TITLE
Code challenge not properly encoded in Auth request

### ISSUE THREAD

**Issue by Trabber** [henalbrod/Blazor.Auth0#12]
A very minimal client only app authenticating against an Identity Server 4 instance on local host generated this auth request:

`https://localhost:44373/connect/authorize?&response_type=code&code_challenge_method=S256code_challenge=fXsiI0JPtBectyE0/rYp6FqujManyFWfwauxq7YljHI=&state=+j3IlMJ2SIVM6z+KZoRZyJiOoErq1yWLOREznqr4ntQ=&nonce=q7TLYSCLQyiAwqXve7VU12XMPKFYESnjZZRCiB+rk8Y=&client_id=debugClientID&scope=openid%20profile%20email&redirect_uri=https://localhost:44391/`

Note the missing ampersand between the `code_challenge_method` and `code_challenge` parameters.

Less important: the query string has an unnecessary & before the first parameter name.

**Comment by henalbrod** [comment]
Thank you for discovering this issue.

I'm currently working on the update to .NET Core 3.0 Preview 7, It'll be ready shortly and will include a fix for this.

**Comment by Trabber** [comment]
Thanks.
