### ISSUE TITLE
Not compiling Client side

### ISSUE THREAD

**Issue by indcoder** [henalbrod/Blazor.Auth0#15]
Added the following package 
Blazor-Auth0-ClientSide -Version 0.7.2-beta.2

and I'm consistently being faced with the following error on running dotnet run under VS Code.

exited with code -532462766

Please check the Nuget package.

**Comment by henalbrod** [comment]
Hi!,

Haven't tested the library on VSCode yet, I'll take a look.

**Comment by henalbrod** [comment]
Sorry but I was unable to reproduce the issue, could you provide more insights about how to reproduce it please?

Also, Blazor-Auth0-ClientSide -Version 0.7.2-beta.2 is compatible with .Net Core Preview 7, please verify all the prerequisites were installed:

1 - You installed the latest [.NET Core 3.0 Preview SDK](https://dotnet.microsoft.com/download/dotnet-core/3.0) release.

2 - You installed the Blazor templates by running the following command in a command shell:
```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview7.19365.7
```

3 - You created the client side blazor project vía command shell:
```
dotnet new blazor
```

4 - You installed the latest [ C# extension for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp)

5 - You added the Blazor.Auth0.ClientSide library by adding a new reference in the .csproj file

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview7.19365.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview7.19365.7" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview7.19365.7" PrivateAssets="all" />

    // == Blazor.Auth0.ClientSide library reference ==
    <PackageReference Include="Blazor-Auth0-ClientSide" Version="0.7.2-beta.2" />
    //===============================

  </ItemGroup>

</Project>
```

**Comment by indcoder** [comment]
Yes @Pegazux it worked postt a restart of the machine, after ugrading to preview 7. Thanks for detailed explanation
