### ISSUE TITLE
Call to authorize endpoint throwing 400

### ISSUE THREAD

**Issue by indcoder** [henalbrod/Blazor.Auth0#16]
Hi,

The call to authorize endpoint is failing with an HTTP code 400

![image](https://user-images.githubusercontent.com/2099300/62087362-16864600-b27f-11e9-822e-b9421b61c7d7.png)

Request URL: https://[domain]/authorize?response_type=code&code_challenge_method=S256&code_challenge=[code challenge]&state=[state]&nonce=[nonce]&client_id=[clientid]&scope=openid%20profile%20email&redirect_uri=https://localhost:5001/&response_mode=web_message&prompt=none

But if I lop off the last two parameters from the URL, it works
&response_mode=web_message&prompt=none

**Comment by henalbrod** [comment]
Hi!

An error 400 is indicating that at least one parameter is wrong, please verify if the provided Auth0 domain and Client Id are correct.

Also, verify the following setting values doesn't contains URLs finished with "/"

* Allowed Callback URLs
* Allowed Web Origins
* Allowed Logout URLs
* Allowed Origins (CORS)

For your example, the value in those should look like this **http://localhost:5001** (without an "/" at the end).

A value like this  http://localhost:5001/  (with an "/" at the end). will result in an Error 400.

**Comment by indcoder** [comment]
Oh yes those are correct...hence the call to Authorize works when I remove
those two parameters only....the other parts of the URL call incl. Domain ,
client id, state, nonce etc are not changed.

**Comment by henalbrod** [comment]
Hi,

I updated my comment, would you please revalidate with the extra info?

**Comment by indcoder** [comment]
1. I'm not setting the Redirect URL in the code ....I'm not sure where Blazor.Auth0 is picking up that value.
2. I tried to make that Authorize call without the trailing slash in the redirect URI but it still failed. Only when I remove the web_message and prompt query, it then works.....even with the trailing slash in the redirect URI

**Comment by henalbrod** [comment]
The settings I mention in my comment are located in the Auth0's Client settings page not in the code.

In your Auth0 account please visit the Applications menu then select the desired application.
#
![Capture1](https://user-images.githubusercontent.com/1284760/62160108-d18efd80-b2d8-11e9-82c7-00809d7619b0.PNG)
#


Then inside the application settings verify the settings I mentioned comments before:
#
![Capture2](https://user-images.githubusercontent.com/1284760/62160109-d18efd80-b2d8-11e9-96ce-2dcebd359030.PNG)

**Comment by indcoder** [comment]
Well this was always my redirect URI ....it did not have the trailing slash

![image](https://user-images.githubusercontent.com/2099300/62160424-9967d900-b331-11e9-96f3-961331c9a5ee.png)



I have not configured anything for "Allowed web origin" and "Allowed Logout urls" They are empty/

**Comment by henalbrod** [comment]
Please include your URLs into those settings also

**Comment by indcoder** [comment]
Thanks....Its working now . Closing the issue
