### ISSUE TITLE
Ability to get Authentication Status in Code Behind

### ISSUE THREAD

**Issue by ITninja04** [henalbrod/Blazor.Auth0#17]
Love what you've done so far, we're using this successfully without any issues so far.

I do have a question however. Is it possible to get the authentication state in the code behind? Specifically we'd like to get access to the claims and user details in Hangfire which is able to get the HTTPContext for the request, but the User is unauthenticated although they are actually authenticated.

Our hangfire issue is a one off I'm sure, the real issue is that the HTTPContext is not showing the user as authenticated.

Any thoughts on how to address this?

Thanks in advance :)

**Comment by henalbrod** [comment]
Hi, 

Glad to know the library have been useful for you.

In order to answer your question, I would like to know which Blazor hosting model are you using, is it Client Side, Server Side or AspNetCore Hosted?

Also, would you mind sharing the code you're using in the ConfigureServices method of your Startup.cs?

**Comment by ITninja04** [comment]
Thanks for the response, we're using Server Side. Here is our ConfigureServices method:


`public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<Data.DataContext>(options => options.UseSqlServer(Configuration.GetConnectionString("MainDB")).EnableSensitiveDataLogging(), ServiceLifetime.Transient);
            services.AddHangfire(configuration => configuration.UseSqlServerStorage(Configuration.GetConnectionString("MainDB_HF")));

            services.AddHangfireServer();
            services.AddOptions();

            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddBlazoredModal();
            services.AddScoped<HttpClient>();

            services.AddScoped((sp) =>
            {
                return new Blazor.Auth0.Shared.Models.ClientSettings()
                {
                    Auth0Domain = Configuration["Auth0:Domain"],
                    Auth0ClientId = Configuration["Auth0:Client_ID"],
                    //LoginRequired = true,
                    GetUserInfoFromIdToken = true,
                    RedirectAlwaysToHome = true,
                    Auth0Audience = "https://api.##########.com"
                };
            });


            services.AddScoped<Blazor.Auth0.ServerSide.Authentication.AuthenticationService>();

            services.Configure<AzureSearchSettings>(Configuration.GetSection("AzureSearch"));
            services.AddSingleton<IConfiguration>(Configuration);

            services.AddScoped<AzureSearchSettings>();


            services.AddScoped<Microsoft.AspNetCore.Components.AuthenticationStateProvider, Blazor.Auth0.ServerSide.Authentication.AuthenticationStateProvider>();
            services.AddFileReaderService();

            services.AddTransient<Services.IBlobStorageService, Services.BlobStorageService>();

            services.AddScoped<Services.IComponentUpdater, Services.ComponentUpdater>();

            services.AddTransient<IEmailSender, EmailSender>();
            services.AddTransient<Data.IDataContextFactory, Data.DataContextFactory>();

            services.AddSweetAlert2();

            services.AddAuthorization(options =>
            {
                options.AddPolicy("ExternalUser", policy => policy.RequireClaim("permission:read:external"));
                options.AddPolicy("AdminUser", policy => policy.RequireClaim("permission:read:admin"));
                options.AddPolicy("SuperAdmin", policy => policy.RequireClaim("permission:read:superadmin"));
                options.AddPolicy("ReadOnly", policy => policy.RequireClaim("permission:read:readonly"));
            });
        }`

**Comment by henalbrod** [comment]
Hi,

It looks like your missing a reference to HttpContextAccessor.

In your ConfigureServices method please add:

```C#
services.AddHttpContextAccessor();
```

And in the desired component (if any) please add:

```C#
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor
``` 

Please let me know if this works for you.

Source: [StackOverflow Question](https://stackoverflow.com/questions/53817373/how-do-i-access-httpcontext-in-server-side-blazor)

**Comment by ITninja04** [comment]
![AspNetCore_Hangfire_Blazor](https://user-images.githubusercontent.com/15346572/62490077-13fb8300-b78e-11e9-9f6f-950ebfb04871.jpg)

I gave that a shot, but the user is still not coming through for some reason :|

**Comment by henalbrod** [comment]
How does your App.razor looks like?

**Comment by ITninja04** [comment]
`<CascadingAuthenticationState>
    <Router AppAssembly="typeof(Startup).Assembly">
        <NotFoundContent>
            <p>Sorry, there's nothing at this address.</p>
        </NotFoundContent>
    </Router>
</CascadingAuthenticationState>`

**Comment by ITninja04** [comment]
If you have a moment I could do a zoom meeting and show it to you.

**Comment by ITninja04** [comment]
Actually, I sent the wrong app.razor. Here's what I have in the actual one:

`
@using Blazor.Auth0.Shared.Models.Enumerations
@using Blazor.Auth0.ServerSide.Components
@using Blazor.Auth0.ServerSide.Authentication
@inject AuthenticationService _authService
@inject Microsoft.AspNetCore.Components.IUriHelper UriHelper
@inject Data.DataContext dbContext
@inject IJSRuntime JsRuntime

<AuthComponent LoginRequiredOnProtectedPaths="true" ProtectedPaths="@protectedPaths">
    <AuthorizingContent>
        <Fish_Partner_Portal.Shared.UIComponents.LoadingOverlay />
    </AuthorizingContent>

    <AuthorizedContent>
        <CascadingAuthenticationState>
            <CascadingValue Value="@UserData" Name="User">
                <Router AppAssembly="typeof(Startup).Assembly">
                    <NotFoundContent>
                        <div id="notfound">
                            <div class="notfound">
                                <div class="notfound-404">
                                    <h1>404</h1>
                                    <h2>Page not found</h2>
                                </div>
                                <a href="/">Homepage</a>
                            </div>
                        </div>
                    </NotFoundContent>
                </Router>
                <Fish_Partner_Portal.Shared.Components.ModalContainer />
            </CascadingValue>

        </CascadingAuthenticationState>

    </AuthorizedContent>

    <NotAuthorizedContent>
        <div id="notfound">
            <div class="notfound">
                <div class="notfound-404">
                    <h1>401</h1>
                    <h2>Unauthorized</h2>
                </div>
                <a href="@_authService.BuildAuthorizeUrl()">Login</a>
            </div>
        </div>
    </NotAuthorizedContent>
</AuthComponent>
`

**Comment by henalbrod** [comment]
Sorry, not able for calling just now :( 

Would you please test the following?

```C#
[CascadingParameter] Task<AuthenticationState> authenticationStateTask { get; set; }

public async Task<bool> Authorize(){

        var authState = await authenticationStateTask;

        var user = authState.User;

        return user.Identity.IsAuthenticated;

}
```

Also, I think that the **CascadingAuthenticationState** component should the outer-most element

**Comment by henalbrod** [comment]
Ok, I think I found a dirty work-around:


**Create new CustomHttpContextAccessor class**

```C#
    public class CustomHttpContextAccessor: IHttpContextAccessor
    {

        private readonly Microsoft.AspNetCore.Components.AuthenticationStateProvider authenticationStateProvider;
        private readonly IHttpContextAccessor httpContextAccessor;

        public CustomHttpContextAccessor(Microsoft.AspNetCore.Components.AuthenticationStateProvider authenticationStateProvider, IHttpContextAccessor httpContextAccessor)
        {
            this.authenticationStateProvider = authenticationStateProvider ?? throw new ArgumentNullException(nameof(authenticationStateProvider));
            this.httpContextAccessor = httpContextAccessor ?? throw new ArgumentNullException(nameof(httpContextAccessor));
        }

        public HttpContext HttpContext { get {

                var authState = Task.Run(async ()=> await authenticationStateProvider.GetAuthenticationStateAsync()).Result;

                httpContextAccessor.HttpContext.User = authState.User;

                return httpContextAccessor.HttpContext;

            } set {

                httpContextAccessor.HttpContext = value;

            }
        }

    }
```

**In Startup.cs**

```C#
public void ConfigureServices(IServiceCollection services)
{

    // ------------- other services  ------------------->>>
    services.AddHttpContextAccessor();            
    services.AddScoped<CustomHttpContextAccessor>();
    // ------------- other services  ------------------->>>

}
```

**In your <component>.razor**

```C#
@inject CustomHttpContextAccessor httpContextAccessor

// ------------- other code ----------------->>>

@code {

    public bool IsAuthorized()
    {

        var httpContext = httpContextAccessor.HttpContext;   
        
        return httpContext.User.Identity.IsAuthenticated;

    }
}

```

**Comment by ITninja04** [comment]
@Pegazux tried that and we're still not getting the logged in user back.

**Comment by henalbrod** [comment]
I see, I guess the httpContextAccessor is reading the user session status from a different place, maybe we're missing a proxy that feeds the HttpContext with the user session info

**Comment by henalbrod** [comment]
@ITninja04 this issue will be resolved with the next version for server side

**Comment by henalbrod** [comment]
The new release is now alive.
