### ISSUE TITLE
Going to Weather page when not logging results in delay before redirect to login

### ISSUE THREAD

**Issue by TopSwagCode** [henalbrod/Blazor.Auth0#19]
Hi. Love the project. I have a problem with CoreHosted Client:
https://github.com/Pegazux/Blazor.Auth0/blob/master/examples/Blazor.Auth0.Examples.CoreHosted.Client/Pages/FetchData.razor
When I browse to this page I get a delay for 30 seconds.
My guess is it is because of " System.Threading.Thread.Sleep(30000); " in:
https://github.com/Pegazux/Blazor.Auth0/blob/master/src/Blazor.Auth0.ServerSide/Components/AuthComponent.razor
Is there a reason for the 30seconds delay? Or just some debug code left behind?

Best regards Joshua Ryder AKA TopSwagCode :)

**Comment by henalbrod** [comment]
Hi! Thanks for the feedback!

This is an unfortunate code left behind. 

I highly recommend you to take a look at the Built-in authentication examples as the custom component is planned to be removed in next release. 

https://github.com/Pegazux/Blazor.Auth0/blob/master/examples/Blazor.Auth0.Examples.BuiltInAuth.ClientSide/App.razor

**Comment by henalbrod** [comment]
The new release without AuthComponent.razor is alive
