### ISSUE TITLE
Feature: Call API

### ISSUE THREAD

**Issue by yiyoMX** [henalbrod/Blazor.Auth0#2]
Hi, Im calling an asp.net core webapi with auth0 authentication enabled from my blazor serverside app, in order to make this plugin more useful it would be great if you can enable access to Retrieved Access Token
"To call your API from a SPA, the application must pass the retrieved Access Token as a Bearer token in the Authorization header of your HTTP request."

**Comment by henalbrod** [comment]
Added new "SessionInfo" property to AuthenticationServiceBase to enable access to Retrieved Access Token
