### ISSUE TITLE
Method GetAuthenticationStateAsync in type 'Blazor.Auth0.ServerSide' does not have an implementation.

### ISSUE THREAD

**Issue by ITninja04** [henalbrod/Blazor.Auth0#22]
Under .NET Core Preview 9 the above error occurs when loading the app. The exception happens when injecting the service on startup.

**Comment by henalbrod** [comment]
Hi,

The upgrade to preview 9 is in the works, this issue will be fixed as soon as the upgrade is ready.

**Comment by enashnash** [comment]
Or jump straight to v3.0.0-rc1, released today 👍

**Comment by henalbrod** [comment]
Was about to finish the upgrade and there's a new release, I'm getting old for this.

**Comment by ITninja04** [comment]
@henalbrod for what it's worth, I for one really appreciate your help!

**Comment by henalbrod** [comment]
v1.0.0.Preview2 Released

Overall upgrade to .Net Core 3.0 RC1
Removed Shell.razor in Example projects
Simplified App.razor in Example projects
Removed local _imports.razor in Example projects
