### ISSUE TITLE
Compile failing for dotnet core RC 1

### ISSUE THREAD

**Issue by indcoder** [henalbrod/Blazor.Auth0#26]
Just downloaded the lastest dotnet core release candidate , it errors out with the linker error code
-532462766.

I'm aware that Readme mention that its tested with Preview 8....just wanted to take it for a spin.

**Comment by jbomhold3** [comment]
You cant compile a preview 8 app with the rc. They did major namespace changes.  Hes working on getting a release out

**Comment by henalbrod** [comment]
v1.0.0.Preview2 Released

* Overall upgrade to .Net Core 3.0 RC1
* Removed Shell.razor in Example projects
* Simplified App.razor in Example projects
* Removed local _imports.razor in Example projects
