### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by jbomhold3** [henalbrod/Blazor.Auth0#27]
Will do a PR but want to make sure our goals align before.
Endpoints should be gathered from the .well-known/openid-configuration  file not hardcoded in. This causes incompatibility with auth servers.

**Comment by henalbrod** [comment]
The main goal of the library is to bring Auth0 into Blazor while keeping its usage/implementation simple and easy.

Also, keeping the client-side version as lightweight as possible, trying to avoid extra references.

That being said, making it play well with other OIDC IdPs won't hurt, but always keeping an eye on the original objectives mentioned above.
