### ISSUE TITLE
Http (not) support in identity server URL in options. 

### ISSUE THREAD

**Issue by megafetis** [henalbrod/Blazor.Auth0#3]
1. Generated auth url is only for https//:{domain}. Please add http

2. If possible, add suport for client secret string property in options. (additionally)

**Comment by henalbrod** [comment]
Hi, could you please elaborate or give some example of the potential use cases that would require this features? Thanks.

**Comment by megafetis** [comment]
Hello! In ClientOptions.cs:
```cs
public bool UseHttps { get; set; } = true;
```
In AuthenticationServiceBase.cs:

```cs
// in constructor
this._protocol = settings.UseHttps ? "https" : "http";

// when generating auth url
var url = $"{_protocol}://{clientSettings.Auth0Domain}/authorize?" + "...";
```
Use cases - my test identity server is working without https in test mode

**Comment by henalbrod** [comment]
Hi,

I'm afraid the auth URL cannot be other than https (even if you call it via http it redirects to https).

You said your test identity server is http only, I would like to know, how the https endpoint is affecting your implementation?

Regarding the client secret: 

Currently, the component doesn't requires it, even the core hosted example uses the intrisic behavior of .Net authentication to verify the token signature.

If the client secret is something you require in your implementation then I can recommend you to use .Net Secrets or including it via environment variables.

**Comment by henalbrod** [comment]
Closing this as no new comments were added
