### ISSUE TITLE
ClientSide: Lose tokens when refresh page

### ISSUE THREAD

**Issue by srpeirce** [henalbrod/Blazor.Auth0#38]
Hello,
I'm just taking a look at the client-side example and have the following problem:

1. Login
2. Refresh the page
3. User is logged out, has to click `Login` again (albeit they don't have to re-enter their credentials).

Is there a way to stop this step of having to re-click `Login`?

Many thanks,
Steve

**Comment by henalbrod** [comment]
Hi!

Looks like you need to set `options.SlidingExpiration = true;` that way the application will try to validate if there's already an active session vía silent login.

If you are following the Client-Side example located [here](https://github.com/henalbrod/Blazor.Auth0/tree/master/examples/Examples.ClientSide), then you just need to uncomment the line 31 in `Startup.cs` file.

You can also find a step by step explanation of how to implement this library in client-side [here](https://dev.to/henalbrod/securing-your-blazor-app-with-auth0-client-side-2c6)

**Comment by srpeirce** [comment]
Cool thanks that's the one :)
Afterwards I realised that I needed to configure `Allowed Web Origins` in Auth0 also.

Thanks for your help, I'm very appreciative of this library - good work 👍

**Comment by OscarCanek** [comment]
I'm still having the issue after set `options.SlidingExpiration = true;` and  `Allowed Web Origins`. I reload the page and I have to login again manually.


<img width="621" alt="image" src="https://user-images.githubusercontent.com/3521524/72467690-146a6200-37a1-11ea-9461-fa25a5a23618.png">

Could you help me?

**Comment by OscarCanek** [comment]
@henalbrod could you help me 'cause I couldn't  find a solution?
