### ISSUE TITLE
Periodic view update causes issues

### ISSUE THREAD

**Issue by ITninja04** [henalbrod/Blazor.Auth0#4]
Every 30 to 45 seconds an iframe will be injected (I assume to validate the users session). During this time it triggers a 'StateHasChanged' method call and causes my components to re-render.

This would be okay for text and other static items but I have on page where we're showing a chart and when it re-renders it animates causing the app to not act naturally.

Is there a way to disable this background refresh?

So far that's the only issue/bug we've seen, we really appreciate you putting in the time on this project!

**Comment by henalbrod** [comment]
Hi,

I really appreciate you take time to test the tool and bring feed back from it, thanks.

I'm closing this to move the discussion to the specific issues opened to address the reported:

[Silent Login interval is too short](https://github.com/Pegazux/Blazor.Auth0/issues/5)
[Unnecesary StateHasChanged event fired on silent login](https://github.com/Pegazux/Blazor.Auth0/issues/6)

**Comment by henalbrod** [comment]
Issues have been addressed commit [bc59de7](https://github.com/Pegazux/Blazor.Auth0/commit/bc59de726548e05b1097d7c353414b423aa90df2)
