### ISSUE TITLE
Refresh Tokens

### ISSUE THREAD

**Issue by kenneymyers** [henalbrod/Blazor.Auth0#7]
Are you considering adding support for refresh tokens?  One thing that our users frequently request is to stay logged in for longer and Auth0 restricts us a bit on how long the tokens last.

**Comment by henalbrod** [comment]
Hi, it's not enough with the automatic silent Login?

5 secs before token's expire time a silent login is run, this effectively generates a new access token, all without user intervention.

In the practice, the user session will last up to when the user logs-out or the application determines to log the user off.

**Comment by kenneymyers** [comment]
You are totally correct.  It's working fine.  Thank you!
