### ISSUE TITLE
No login button on new setup

### ISSUE THREAD

**Issue by yiyoMX** [henalbrod/Blazor.Auth0#8]
The getting started instructions from preview <5 had a login/logout button already coded in, but in the new instructions for preview 6 there isnt, is this intentional?

**Comment by henalbrod** [comment]
No it's not, I'm going to review.

**Comment by henalbrod** [comment]
You're totally right, and this is not the idea; I'm going to fix example to
include a login/Logout button, thanks for the catch up.

**Comment by kenneymyers** [comment]
Well thanks for keeping this updated but wow preview 6 is totally incompatible with our existing applications.  I hope Microsoft doesn't keep completely changing basic concepts with Blazor.  I am going to attempt to retrofit my apps with the examples.  Fingers crossed.

**Comment by henalbrod** [comment]
An explanatory note was included in the steps and also a link to one of the examples implementing Login/Logout Button flow. Closing.
