### ISSUE TITLE
Google Social Connection: Login not successful

### ISSUE THREAD

**Issue by m4cx** [henalbrod/Blazor.Auth0#9]
Hi,

I am just playing around with this awesome library for Blazor. Thanks for your efforts. But I am currently stuck with the handling of the returning code from Auth0. I completely can login using Auth0 and my Google Account, but when I am redirected back to the Blazor application, I am still recognized as Unauthorized / not logged in. 

In my Auth0 Console I see a failing silent login. 

Did I miss something?

I also tested your examples (proprietary as well as built-in) with my Auth0 Account but both didn't work.

Any suggestions?

**Comment by henalbrod** [comment]
Hi,

Would you please confirm if in your Auth0 Client's setting page:

- What kind of Application Type is set?
- Is your application URL included in Allowed Callback URLs, Allowed Web Origins, Allowed Logout URLs, and Allowed Origins (CORS)?
- Authorization code grant is selected in Advanced Settings on the client's settings page?

Finally, if you can share the logs from the application and Auth0 would help to determine the source of the issue.

**Comment by m4cx** [comment]
- Single Page Application
- Yes they are: (see screenshot as proof :smile: ) ![grafik](https://user-images.githubusercontent.com/363497/59692480-4dc7f880-91e5-11e9-83d7-222f2f3aae02.png)
- Authorization Code is selected ![grafik](https://user-images.githubusercontent.com/363497/59692561-836ce180-91e5-11e9-93b7-2c77ec7e4609.png)

Your renaming made me check the local user & password authentication. That works totally fine and helps me for my demo case so far. But having Google Auth in place would be awesome anyway 😄

**Comment by henalbrod** [comment]
Just to be 100% clear, you're using your own Google Account, correct?

**Comment by m4cx** [comment]
Sure!

**Comment by henalbrod** [comment]
Please indicate what Universal Login version are you using The Classic one or the new one?

**Comment by m4cx** [comment]
It seems I am using the classic one:
![grafik](https://user-images.githubusercontent.com/363497/59694921-a7322680-91e9-11e9-99fb-285cf6e351f7.png)

**Comment by henalbrod** [comment]
Could you please test by using the new one? and if that doesn't help, while using the new one, test by using the default Auth0's Google connection (by removing your current google connection), please?

**Comment by henalbrod** [comment]
mmmm, now that I think, we were talking about "Google Accounts" but not "Google Apps", did you created an app in Google and set it up as a social connection in Auth0? or your Google Social connection in auth0 looks like in the picture?

![Capture](https://user-images.githubusercontent.com/1284760/59695406-cdd36b80-91af-11e9-852b-c3a763c42595.PNG)

**Comment by m4cx** [comment]
Okay... using the new Login Form it works fine with google. I did not create an App within Google. I just have the option available in the Connections tab of the application:
![grafik](https://user-images.githubusercontent.com/363497/59696668-be264800-91ec-11e9-8a27-79d1532a14ff.png)

**Comment by henalbrod** [comment]
My totally bad, that would be the very first question to ask, my apologies. 

FYI the classic version has an issue with the default Google social connection, it basically always returns 401 to the client app, the new version doesn't have that issue. 

The Classic version works OK when we configure our own Google App as social connection.

Closing this as it is an ad hoc issue.

**Comment by m4cx** [comment]
Didn't know about the flaw in Auth0. But we fixed this. Thank you very much for your help. I appreciate that.
